# Generated by Django 3.0.7 on 2021-04-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Account_Data',
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customer_Data',
        ),
    ]
