# Generated by Django 3.1.7 on 2021-04-18 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210414_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECS_Data',
            fields=[
                ('ECS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Payer_Name', models.CharField(max_length=300)),
                ('Upper_Limit', models.FloatField()),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.account_data')),
            ],
            options={
                'db_table': 'ecs',
            },
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField()),
                ('Completed', models.BooleanField()),
                ('ECS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ecs_data')),
            ],
            options={
                'db_table': 'bills',
            },
        ),
    ]
